

# This file was *autogenerated* from the file triangle.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9)# triangle.sage
# four triangle problem (from some youtube)

var("a b c d e f")
eqn = [ a+f == _sage_const_6 
      , c+d == _sage_const_6 
      , b+e == _sage_const_6 
      , _sage_const_4 *f == f+c+e
      , _sage_const_4 *(f+c) == f+c +e+b
      , _sage_const_9 *f == f+c+e+b+d
      ]
sol = solve( eqn, [a,b,c,d,e,f] )
ans = (a+b+c).subs( sol )
print(ans)

